"""adding unique constraint to friends tables

Revision ID: 48290775fe33
Revises: 756c74fefcbf
Create Date: 2022-08-17 15:06:28.659088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48290775fe33'
down_revision = '756c74fefcbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'friend_requests', ['user_id', 'friend_id'])
    op.create_unique_constraint(None, 'friends', ['user_id', 'friend_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='unique')
    op.drop_constraint(None, 'friend_requests', type_='unique')
    # ### end Alembic commands ###
