"""added foreign key compliance for new q database field

Revision ID: 756c74fefcbf
Revises: cd279ec00b66
Create Date: 2022-08-15 15:03:51.764990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756c74fefcbf'
down_revision = 'cd279ec00b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asked_questions', sa.Column('original_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asked_questions', 'questions', ['original_id'], ['question_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asked_questions', type_='foreignkey')
    op.drop_column('asked_questions', 'original_id')
    # ### end Alembic commands ###
