"""Initial migration.

Revision ID: 79e4209a4a42
Revises: 
Create Date: 2022-08-10 15:03:24.121006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e4209a4a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_display_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_display_name_key', 'users', ['display_name'])
    # ### end Alembic commands ###
