"""remove font column, simply theme instead

Revision ID: b06587f016e0
Revises: d252c8eae5c5
Create Date: 2022-08-18 02:01:31.161432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06587f016e0'
down_revision = 'd252c8eae5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'font')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('font', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
