"""questions db table update

Revision ID: cd279ec00b66
Revises: 79e4209a4a42
Create Date: 2022-08-14 20:22:43.329123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd279ec00b66'
down_revision = '79e4209a4a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'date_asked',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'date_asked',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
