"""changed daily question functionality, only one questions table now

Revision ID: d252c8eae5c5
Revises: 48290775fe33
Create Date: 2022-08-17 20:34:44.641673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd252c8eae5c5'
down_revision = '48290775fe33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asked_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asked_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['original_id'], ['questions.question_id'], name='asked_questions_original_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='asked_questions_pkey')
    )
    # ### end Alembic commands ###
